# Generated by Django 5.1.7 on 2025-03-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('Rollno', models.PositiveIntegerField()),
                ('name', models.TextField()),
                ('department', models.TextField()),
                ('phone', models.PositiveBigIntegerField()),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
